
#version: "3.9"

services:
  db:
#    platform: linux/x86_64
    image: mysql:5.7
    volumes:
      - db_data:/var/lib/mysql
    #restart: always
    ports:
    - 3360:3366
    network:
      -microservices-net
    restart: unless-stopped


    environment:
#      MYSQL_ROOT_PASSWORD: somewordpress
#      MYSQL_DATABASE: lending
      MYSQL_USER: root
      MYSQL_PASSWORD: unclelove68


      mail-dev:
        container_name: ms-mail-dev
        image: maildev/maildev
        ports:
          - 1080:1080
          - 1025:1025

  networks:
    microservices-net:
      driver: bridge

  redis:
    image: redis
    ports:
    - 6379:6379

volumes:
  db_data: